'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api,Merchant} from '../lib/api';
import AppNav from './AppNav';
import {ArrowLeft,Check,Wallet,LogOut} from './Icons';
import WalletConnect from './WalletConnect';
import {userFacingError} from '../lib/userFacingError';

export default function ProfileClient({merchantId}:{merchantId:string}){
 const [m,setM]=useState<Merchant|null>(null),[name,setName]=useState(''),[tag,setTag]=useState(''),[username,setUsername]=useState(''),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''),[err,setErr]=useState('');
 useEffect(()=>{api.getMerchant(merchantId).then(x=>{setM(x);setName(x.profile?.businessName||'');setTag(x.profile?.tagline||'');setUsername(x.profile?.slug||'')}).catch(e=>setErr(userFacingError(e,'Could not load your profile.')))},[merchantId]);
 async function save(){setSaving(true);setErr('');try{await api.updateMerchant(merchantId,{businessName:name,tagline:tag,username:username.trim()||undefined});setMsg('Profile saved');setTimeout(()=>setMsg(''),2200)}catch(e:any){setErr(userFacingError(e,'Could not save your profile.'))}finally{setSaving(false)}}
 function logout(){api.clearStoredSession();window.dispatchEvent(new Event('celodesk-session'));window.location.href='/'}
 return <div className="appShell"><div className="topbar"><div className="topbarInner"><Link href={`/dashboard?merchantId=${merchantId}`} className="brand"><span className="brandMark"/>CeloDesk</Link><Link href={`/dashboard?merchantId=${merchantId}`} className="btn btnGhost"><ArrowLeft size={17}/>Back</Link></div></div><div className="appPage"><div className="container appGrid"><AppNav merchantId={merchantId}/><main className="main"><div className="profileHero"><div className="profileHeroTop"><div className="avatar"><span className="brandMark" style={{width:38,height:38,borderRadius:13}}/></div><div><div style={{color:'#b4ccc2',fontSize:10}}>BUSINESS PROFILE</div><h1 style={{fontFamily:'Manrope',margin:'4px 0',fontSize:28}}>{name||'Your business'}</h1><div style={{color:'#b4ccc2',fontSize:11}}>{tag||'Add a tagline for your invoices'}</div></div><div className="profileHeroWallet"><WalletConnect compact/></div></div></div><section className="panel profileForm"><div className="formGrid"><div className="field full"><label>Business name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Bello Designs"/></div><div className="field full"><label>Tagline</label><input value={tag} onChange={e=>setTag(e.target.value)} placeholder="Freelance · UI/UX · Web Development"/></div><div className="field"><label>Username</label><input value={username} onChange={e=>setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'').slice(0,30))} placeholder="your-unique-username"/><small className="muted">Unique public username.</small></div><div className="field"><label>Wallet</label><input value={m?.walletAddress||''} readOnly/><small className="muted">Your connected wallet is your account identity.</small></div></div><div style={{display:'flex',gap:10,alignItems:'center',marginTop:22,flexWrap:'wrap'}}><button className="btn btnBrand" onClick={save} disabled={saving||!name}>{saving?'Saving…':<><Check size={16}/>Save changes</>}</button>{msg&&<span style={{fontSize:12,color:'var(--brandDeep)'}}>{msg}</span>}</div>{err&&<div style={{marginTop:14,color:'var(--danger)',fontSize:12}}>{err}</div>}<div className="receipt" style={{marginTop:25}}><div className="receiptRow"><span>Receiving wallet</span><strong>{m?.walletAddress?m.walletAddress.slice(0,7)+'…'+m.walletAddress.slice(-5):'—'}</strong></div><div className="receiptRow"><span>Settlement</span><strong><Wallet size={14}/> Celo Mainnet</strong></div></div><div className="accountDanger"><div><strong>Session</strong><p className="muted">Disconnect this wallet from CeloDesk on this device.</p></div><button className="iconOnlyDanger" onClick={logout} title="Disconnect and log out" aria-label="Disconnect and log out"><LogOut size={17}/></button></div></section></main></div></div></div>
}
