'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api,Invoice,money,shortAddress} from '../../../../lib/api';
import AppNav from '../../../../components/AppNav';
import {ArrowLeft,Copy,Share,Receipt} from '../../../../components/Icons';
import {StatusBadge} from '../../../../components/StatusBadge';
import {userFacingError} from '../../../../lib/userFacingError';

export default function Page({params,searchParams}:{params:{id:string};searchParams:{merchantId?:string}}){
 const merchantId=searchParams.merchantId||''; const [invoice,setInvoice]=useState<Invoice|null>(null); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
 useEffect(()=>{api.getInvoice(params.id).then(setInvoice).catch(e=>setError(userFacingError(e,'Could not load this invoice.')))},[params.id]);
 async function copyLink(){if(!invoice)return;const url=`${window.location.origin}/invoice/${invoice.publicSlug}`;await navigator.clipboard?.writeText(url);setNotice('Payment link copied');setTimeout(()=>setNotice(''),1800)}
 if(error)return <div className="appShell"><div className="topbar"><div className="topbarInner"><Link href={`/dashboard/invoices?merchantId=${merchantId}`} className="btn btnGhost"><ArrowLeft size={16}/>Back</Link></div></div><main className="main container"><div className="formError"><strong>{error}</strong><div className="checkoutErrorActions"><button className="btn btnBrand" onClick={()=>window.location.reload()}>Try again</button><Link className="btn btnSoft" href={`/dashboard/invoices?merchantId=${merchantId}`}>Cancel</Link></div></div></main></div>;
 return <div className="appShell"><div className="topbar"><div className="topbarInner"><Link href={`/dashboard/invoices?merchantId=${merchantId}`} className="brand"><span className="brandMark"/>CeloDesk</Link><Link href={`/dashboard/invoices?merchantId=${merchantId}`} className="btn btnGhost"><ArrowLeft size={16}/>Back</Link></div></div><div className="appPage"><div className="container appGrid"><AppNav merchantId={merchantId}/><main className="main">{notice&&<div className="successToast">{notice}</div>}<div className="pageTitleRow"><div><div className="muted" style={{fontSize:11}}>INVOICE DETAILS</div><h1>{invoice?.clientName||'Invoice'}</h1><p className="muted">Internal invoice record — customer payment page is separate.</p></div>{invoice&&<div className="invoiceDetailActions"><button className="btn btnSoft" onClick={copyLink}><Copy size={15}/>Copy payment link</button><Link className="btn btnBrand" href={`/invoice/${invoice.publicSlug}`} target="_blank"><Share size={15}/>Open payment page</Link></div>}</div>{invoice?<section className="panel" style={{padding:24}}><div className="invoiceClient" style={{marginBottom:18}}><span className="clientDot"><Receipt size={16}/></span><strong>{invoice.clientName}</strong><StatusBadge status={invoice.status}/></div><div className="checkoutAmount">{money(invoice.amount,invoice.tokenSymbol)}</div><p className="muted">{invoice.description||'Payment request'}</p><hr style={{margin:'22px 0',border:0,borderTop:'1px solid var(--border)'}}/><div className="detailGrid"><div><span className="muted">Created</span><strong>{new Date(invoice.createdAt).toLocaleString()}</strong></div><div><span className="muted">Due date</span><strong>{invoice.dueDate?new Date(invoice.dueDate).toLocaleDateString():'No due date'}</strong></div><div><span className="muted">Receiving wallet</span><strong>{shortAddress(invoice.receivingWallet)}</strong></div><div><span className="muted">Network</span><strong>Celo Mainnet</strong></div></div>{invoice.payments?.length?<div style={{marginTop:26}}><h3>Payment history</h3>{invoice.payments.map(p=><div key={p.id} className="invoiceRow"><span>{money(p.amount,invoice.tokenSymbol)}</span><span className="muted">{p.status}</span><span className="muted">{shortAddress(p.txHash)}</span></div>)}</div>:<p className="muted" style={{marginTop:24}}>No payments recorded yet.</p>}</section>:<section className="panel" style={{padding:24}}>Loading invoice…</section>}</main></div></div></div>}
